<#
.SYNOPSIS
    Generates Intune-ready detection and remediation scripts from a JSON configuration.

.DESCRIPTION
    Reads the sibling Invoke-RegistryConfigEngine.ps1 and produces two self-contained
    PowerShell scripts by replacing the engine's INJECTION_POINT region with the
    embedded config and the forced mode. The engine itself is the single source of
    truth — there is no separate template.

.PARAMETER ConfigPath
    Path to the JSON configuration file to package.

.PARAMETER OutputPath
    Directory where the Detect/Remediate scripts will be written. Default: current directory.

.PARAMETER Prefix
    Prefix for the generated filenames. Default: config filename without extension.

.PARAMETER VerboseLogging
    If specified, generated scripts run with $VerbosePreference = 'Continue', which
    surfaces all Write-Verbose/Debug-level engine output to Intune. No custom flag.

.EXAMPLE
    .\New-IntunePackage.ps1 -ConfigPath .\Configs\01-corporate-branding.json

.NOTES
    Author: Haakon Wibe
    Blog:   https://alttabtowork.com
#>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$ConfigPath,

    [Parameter(Position = 1)]
    [string]$OutputPath = ".",

    [Parameter()]
    [string]$Prefix,

    [Parameter()]
    [switch]$VerboseLogging
)

$ErrorActionPreference = 'Stop'

# Resolve the engine sibling
$enginePath = Join-Path $PSScriptRoot 'Invoke-RegistryConfigEngine.ps1'
if (-not (Test-Path -LiteralPath $enginePath)) {
    throw "Engine not found at: $enginePath"
}

# Dot-source the engine so the package-time pre-flight uses its Assert-ValidConfig —
# the exact same validation rules (and enums) as the runtime load, single source of
# truth. The engine is dot-source-safe (a guard around Main Execution skips it), but
# its param() block is still processed and would overwrite our $ConfigPath with the
# engine's empty default, so save and restore it across the dot-source.
$savedConfigPath = $ConfigPath
. $enginePath
$ConfigPath = $savedConfigPath

# Read + validate the config via the engine's shared validator. A rejected config
# is a user-facing outcome, not a generator bug, so report the reason on one line
# and exit 1 — under $ErrorActionPreference = 'Stop' an uncaught throw here buries
# the message in a CategoryInfo/FullyQualifiedErrorId stack dump. Nothing has been
# written at this point, so there is no partial package to clean up.
try {
    $configJson = Get-Content -Path $ConfigPath -Raw -Encoding UTF8

    # A here-string is terminated by `'@` at column 0. JSON syntax doesn't allow
    # that on its own line, but reject it loudly if encountered rather than
    # producing a silently-broken script.
    if ($configJson -match "(?m)^'@") {
        throw "Configuration JSON contains a line beginning with `'@` which would terminate the embedded here-string. Reformat the source JSON."
    }

    $config = $configJson | ConvertFrom-Json
    Assert-ValidConfig -Config $config
}
catch {
    Write-Host "Configuration rejected: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "No package files were written." -ForegroundColor Red
    exit 1
}

# Engine source (for the INJECTION_POINT replacement) and its version. The version
# is now available directly from the dot-sourced engine, no need to re-parse it.
$engineSrc = Get-Content -Path $enginePath -Raw -Encoding UTF8
$engineVersion = $script:EngineVersion

# Set up output directory + naming
if (-not (Test-Path -LiteralPath $OutputPath)) {
    New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null
}
if ([string]::IsNullOrEmpty($Prefix)) {
    $Prefix = [System.IO.Path]::GetFileNameWithoutExtension($ConfigPath)
}

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz'
$sourceName = Split-Path -Leaf $ConfigPath
$injectionPattern = '(?s)#region INJECTION_POINT.*?#endregion'
$verboseLine = if ($VerboseLogging) { "`r`n`$VerbosePreference        = 'Continue'" } else { '' }

function Build-Script {
    param([Parameter(Mandatory)][ValidateSet('Detect', 'Remediate')][string]$Mode)

    $injection = @"
#region INJECTION_POINT
# Auto-generated by New-IntunePackage.ps1 — DO NOT EDIT
`$script:__EmbeddedConfig = @'
$configJson
'@
`$script:__ForcedMode     = '$Mode'
`$script:__ForcedEventLog = `$true$verboseLine
#endregion
"@

    $header = @"
# ============================================================================
# Registry Configuration Engine — $Mode (packaged for Intune)
# Engine version : $engineVersion
# Source config  : $sourceName
# Generated      : $timestamp
# DO NOT EDIT — regenerate via New-IntunePackage.ps1
# ============================================================================

"@

    # MatchEvaluator form avoids any $-escaping concerns in the replacement string.
    $body = [regex]::Replace($engineSrc, $injectionPattern, { param($m) $injection })

    # The header here-strings and the engine body can carry different line
    # endings (this script vs the engine source on disk). Normalize to a single
    # CRLF style and strip trailing whitespace so the generated package is
    # consistent and clean under PSScriptAnalyzer.
    $text = $header + $body
    $text = $text -replace "`r`n", "`n" -replace "`r", "`n"
    $text = $text -replace '[ \t]+(?=\n)', '' -replace '[ \t]+$', ''
    $text -replace "`n", "`r`n"
}

$detectPath    = Join-Path $OutputPath "$Prefix-Detect.ps1"
$remediatePath = Join-Path $OutputPath "$Prefix-Remediate.ps1"

(Build-Script -Mode 'Detect')    | Set-Content -Path $detectPath    -Encoding UTF8 -NoNewline
(Build-Script -Mode 'Remediate') | Set-Content -Path $remediatePath -Encoding UTF8 -NoNewline

Write-Host "Generated:" -ForegroundColor Green
Write-Host "  $detectPath"
Write-Host "  $remediatePath"
Write-Host "Engine v$engineVersion | Settings groups: $($config.settings.Count)" -ForegroundColor Cyan
if ($VerboseLogging) { Write-Host "Verbose logging: enabled" -ForegroundColor Cyan }
